
DROP DATABASE IF EXISTS lezioni_di_canto;
CREATE DATABASE IF NOT EXISTS lezioni_di_canto;

USE lezioni_di_canto;

-- USATA PER CREARE LA TABELLA UTENTI NECESSARIA PER LA PAGINA DI REGISTRAZIONE
CREATE TABLE utenti (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(50) NOT NULL,
    cognome VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    phone VARCHAR(20),
    password VARCHAR(255) NOT NULL,
    data_registrazione DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- USATA PER SALVARE LE RECENSIONI DEGLI UTENTI
CREATE TABLE recensioni (
    id INT AUTO_INCREMENT PRIMARY KEY,
    utente INT,
    voto INT NOT NULL,
    testo VARCHAR(200) NOT NULL,
    data_inserimento DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (utente) REFERENCES utenti(id)
);

-- USATA PER CREARE LA TABELLA DELLE PRENOTAZIONI DELLE LEZIONI
CREATE TABLE prenotazioni (
    id INT AUTO_INCREMENT PRIMARY KEY,
    utente INT,
    descrizione VARCHAR(200),
    fascia_oraria VARCHAR(30),
    note VARCHAR(200),
    data_inserimento DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (utente) REFERENCES utenti(id)
);


